<a href="https://colab.research.google.com/github/allhoesnobros/experinment-11/blob/main/unit_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#DATASET creation
import pandas as pd
data = {
    "Roll_no":[101,102,103,104,105],
    "Gender":["Female", "Male", "Female", "Male", "Female"],
    "department":["cs", "it", "entc", "aiml", "civil"],
    "CGPA":[8.2, 2.8, 8, 9, 9.2]
}
df = pd.DataFrame(data)
print(df)

   Roll_no  Gender department  CGPA
0      101  Female         cs   8.2
1      102    Male         it   2.8
2      103  Female       entc   8.0
3      104    Male       aiml   9.0
4      105  Female      civil   9.2

In [ ]:
df.to_csv("students.csv, index=false")
df

   Roll_no  Gender department  CGPA
0      101  Female         cs   8.2
1      102    Male         it   2.8
2      103  Female       entc   8.0
3      104    Male       aiml   9.0
4      105  Female      civil   9.2

In [ ]:
df.shape

(5, 4)

In [ ]:
df.size

20

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_no     5 non-null      int64
 1   Gender      5 non-null      object
 2   department  5 non-null      object
 3   CGPA        5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [ ]:
df.describe()

          Roll_no      CGPA
count    5.000000  5.000000
mean   103.000000  7.440000
std      1.581139  2.643483
min    101.000000  2.800000
25%    102.000000  8.000000
50%    103.000000  8.200000
75%    104.000000  9.000000
max    105.000000  9.200000

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Cars93.csv')
print(df)

   Manufacturer    Model     Type  Price  MPG.city             AirBags  \
0         Acura  Integra    Small   15.9        25                 NaN
1         Acura   Legend  Midsize   33.9        18  Driver & Passenger
2          Audi       90  Compact   29.1        20         Driver only
3          Audi      100  Midsize   37.7        19  Driver & Passenger
4           BMW     535i  Midsize   30.0        22         Driver only
..          ...      ...      ...    ...       ...                 ...
88   Volkswagen  Eurovan      Van   19.7        17                 NaN
89   Volkswagen   Passat  Compact   20.0        21                 NaN
90   Volkswagen  Corrado   Sporty   23.3        18                 NaN
91        Volvo      240  Compact   22.7        21         Driver only
92        Volvo      850  Midsize   26.7        20  Driver & Passenger

    Horsepower  Passengers  Rear.seat.room  Luggage.room
0          140           5            26.5          11.0
1          200           5            30.0          15.0
2          172           5            28.0          14.0
3          172           6            31.0          17.0
4          208           4            27.0          13.0
..         ...         ...             ...           ...
88         109           7            34.0           NaN
89         134           5            31.5          14.0
90         178           4            26.0          15.0
91         114           5            29.5          14.0
92         168           5            30.0          15.0

[93 rows x 10 columns]

In [ ]:
df.size

930

In [ ]:
df.shape

(93, 10)

In [ ]:
df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000
mean,19.509677,22.365591,143.827957,5.086022,27.829670,13.890244
std,9.659430,5.619812,52.374410,1.038979,2.989072,2.997967
min,7.400000,15.000000,55.000000,2.000000,19.000000,6.000000
25%,12.200000,18.000000,103.000000,4.000000,26.000000,12.000000
50%,17.700000,21.000000,140.000000,5.000000,27.500000,14.000000
75%,23.300000,25.000000,170.000000,6.000000,30.000000,15.000000
max,61.900000,46.000000,300.000000,8.000000,36.000000,22.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [ ]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [ ]:
df.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.sample(67)

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
48,Lexus,ES300,Midsize,28.0,18,Driver only,185,5,27.5,14.0
31,Ford,Escort,Small,10.1,23,NaN,127,5,28.0,12.0
17,Chevrolet,Caprice,Large,18.8,17,Driver only,170,6,29.5,20.0
67,Oldsmobile,Achieva,Compact,13.5,24,NaN,155,5,28.0,14.0
9,Cadillac,DeVille,Large,34.7,16,Driver only,200,6,35.0,18.0
...,...,...,...,...,...,...,...,...,...,...
45,Hyundai,Scoupe,Sporty,10.0,26,NaN,92,4,23.5,9.0
18,Chevrolet,Corvette,Sporty,38.0,17,Driver only,300,2,NaN,NaN
47,Infiniti,Q45,Midsize,47.9,17,Driver only,278,5,29.0,15.0
65,Nissan,Quest,Van,19.1,17,NaN,151,7,27.0,NaN
16,Chevrolet,Astro,Van,16.6,15,NaN,165,8,33.5,NaN

In [ ]:
df.isnull().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.nunique()

Manufacturer      32
Model             93
Type               6
Price             81
MPG.city          21
AirBags            2
Horsepower        57
Passengers         6
Rear.seat.room    24
Luggage.room      16
dtype: int64